# Generated by Django 5.0.3 on 2024-03-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='hira.mushtaq@alrafayconsulting.com', max_length=254, verbose_name=''),
        ),
        migrations.AddField(
            model_name='post',
            name='firstname',
            field=models.CharField(default='Hira', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='lastname',
            field=models.CharField(default='Mushtaq', max_length=50),
        ),
    ]
